export const logos = [
    {
        name: 'colby',
        image: 'https://www.colby.edu/signature/images/Colby.png',
        url: 'https://www.colby.edu',
        height: 'auto',
        width: '96px',
        offset: '12px',
    },
    {
        name: 'colbyBlack',
        image: 'https://www.colby.edu/signature/images/colby_black.png',
        url: 'https://www.colby.edu',
        height: 'auto',
        width: '96px',
        offset: '12px',
    },
    {
        name: 'buckLab',
        image: 'https://www.colby.edu/signature/images/buck_lab.png',
        url: 'https://www.colby.edu/buck-lab-for-climate-and-environment/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'jewishLife',
        image: 'https://www.colby.edu/signature/images/jewish_life.png',
        url: 'https://jewishlife.colby.edu/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'ctl',
        image: 'https://www.colby.edu/signature/images/ctl.png',
        url: 'https://www.colby.edu/center-for-teaching-and-learning/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'cah',
        image: 'https://www.colby.edu/signature/images/cah.png',
        url: 'https://cah.colby.edu/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'colbyArts',
        image: 'https://www.colby.edu/signature/images/colby_arts.png',
        url: 'https://arts.colby.edu/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'colbyAthletics',
        image: 'https://www.colby.edu/signature/images/colby_athletics.png',
        url: 'https://colbyathletics.com/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'museum',
        image: 'https://www.colby.edu/signature/images/museum.png',
        url: 'https://museum.colby.edu/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'davisAI',
        image: 'https://www.colby.edu/signature/images/davis_ai.png',
        url: 'https://davisinstituteai.colby.edu/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'davisConnects',
        image: 'https://www.colby.edu/signature/images/davis_connects.png',
        url: 'https://davisconnects.colby.edu/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
    {
        name: 'farnhamWC',
        image: 'https://www.colby.edu/signature/images/farnham_wc.png',
        url: 'https://www.colby.edu/people/offices-directory/farnham-writers-center/',
        height: 'auto',
        width: '100px',
        offset: '-6px',
    },
    {
        name: 'goldfarb',
        image: 'https://www.colby.edu/signature/images/goldfarb.png',
        url: 'https://goldfarbcenter.colby.edu/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
    {
        name: 'halloran',
        image: 'https://www.colby.edu/signature/images/halloran.png',
        url: 'https://www.colby.edu/halloran-lab-for-entrepreneurship/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
    {
        name: 'lindePackman',
        image: 'https://www.colby.edu/signature/images/linde_packman.png',
        url: 'https://www.colby.edu/people/offices-directory/linde-packman-lab-for-biosciences-innovation/',
        height: 'auto',
        width: '150px',
        offset: '-6px',
    },
    {
        name: 'lunder',
        image: 'https://www.colby.edu/signature/images/lunder.png',
        url: 'https://lunderinstitute.colby.edu/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
    {
        name: 'lyons',
        image: 'https://www.colby.edu/signature/images/lyons.png',
        url: 'https://arts.colby.edu/lyons-arts-lab/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
    {
        name: 'oak',
        image: 'https://www.colby.edu/signature/images/oak.png',
        url: 'https://oakinstitute.colby.edu/',
        height: 'auto',
        width: '120px',
        offset: '-6px',
    },
];
