export const logos = [
    {
        name: 'colby',
        image: 'https://www.colby.edu/signature/images/Colby.png',
        url: 'https://www.colby.edu',
        height: 'auto',
        width: '96',
        offset: '12px',
    },
    {
        name: 'buckLab',
        image: 'https://www.colby.edu/signature/images/buck_lab2.png',
        url: 'https://www.colby.edu/buck-lab-for-climate-and-environment/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'jewishLife',
        image: 'https://www.colby.edu/signature/images/jewish_life2.png',
        url: 'https://jewishlife.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'ctl',
        image: 'https://www.colby.edu/signature/images/ctl2.png',
        url: 'https://www.colby.edu/center-for-teaching-and-learning/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'cah',
        image: 'https://www.colby.edu/signature/images/cah2.png',
        url: 'https://cah.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'colbyArts',
        image: 'https://www.colby.edu/signature/images/colby_arts.png',
        url: 'https://arts.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'colbyAthletics',
        image: 'https://www.colby.edu/signature/images/colby_athletics.png',
        url: 'https://colbyathletics.com/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'museum',
        image: 'https://www.colby.edu/signature/images/museum2.png',
        url: 'https://museum.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'davisAI',
        image: 'https://www.colby.edu/signature/images/davis_ai2.png',
        url: 'https://davisinstituteai.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'davisConnects',
        image: 'https://www.colby.edu/signature/images/davis_connects2.png',
        url: 'https://davisconnects.colby.edu/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'farnhamWC',
        image: 'https://www.colby.edu/signature/images/farnham_wc2.png',
        url: 'https://www.colby.edu/people/offices-directory/farnham-writers-center/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'goldfarb',
        image: 'https://www.colby.edu/signature/images/goldfarb2.png',
        url: 'https://goldfarbcenter.colby.edu/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'halloran',
        image: 'https://www.colby.edu/signature/images/halloran2.png',
        url: 'https://www.colby.edu/halloran-lab-for-entrepreneurship/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'lindePackman',
        image: 'https://www.colby.edu/signature/images/linde_packman2.png',
        url: 'https://www.colby.edu/people/offices-directory/linde-packman-lab-for-biosciences-innovation/',
        height: 'auto',
        width: '150',
        offset: '-6px',
    },
    {
        name: 'lunder',
        image: 'https://www.colby.edu/signature/images/lunder2.png',
        url: 'https://lunderinstitute.colby.edu/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'lunderVertical',
        image: 'https://www.colby.edu/signature/images/lunder_vertical.png',
        url: 'https://lunderinstitute.colby.edu/',
        height: 'auto',
        width: '100',
        offset: '-6px',
    },
    {
        name: 'lyons',
        image: 'https://www.colby.edu/signature/images/lyons2.png',
        url: 'https://arts.colby.edu/lyons-arts-lab/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'oak',
        image: 'https://www.colby.edu/signature/images/oak2.png',
        url: 'https://oakinstitute.colby.edu/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
    {
        name: 'publicPolicy',
        image: 'https://www.colby.edu/signature/images/public_policy.png',
        url: 'https://www.colby.edu/people/offices-directory/public-policy-lab/',
        height: 'auto',
        width: '120',
        offset: '-6px',
    },
];
