name: colby
recipe: wordpress
config:
    webroot: web
    via: nginx
    config:
      vhosts: ./project/lando/wordpress.conf
env_file:
    - lando.env

services:
  node:
    type: node:20
    overrides:
      working_dir: /app/web/wp-content/themes/colby-college-theme-inertia
    ports:
      - 5173
    environment:
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
      VITE_FORCE_POLLING: "1"
    command: "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
  appserver:
    type: php:8.3
    build:
        # Intall the platform.sh CLI and make sure it is up to date.
        - "./scripts/lando-platform-install.sh"
    run:
      - "platform self-update -y"
      - "./scripts/setup-mu-plugins.sh"
      - ./scripts/symlink.sh /app/web/wp-content/mu-plugins/wordpress-seo/wp-seo.php /app/web/wp-content/mu-plugins/wp-seo.php
events:
  post-start:
    # Install composer dependencies
    - "cd /app && composer install"

tooling:
  npm:
    service: node
  npx:
    service: node

proxy:
  node:
    - vite.lndo.site:5173