# Chatbot API Application Configuration
name: chatbot-api

# Python runtime
type: python:3.11

# Application size
size: M

# Build configuration
hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt

# Web server configuration
web:
  commands:
    start: "uvicorn api:app --host 0.0.0.0 --port $PORT --workers 2"
  
  locations:
    /:
      passthru: true
      allow: false

# Disk space for temporary files
disk: 512

# Mounts for writable directories
mounts:
  'tmp':
    source: local
    source_path: tmp

# This app uses the existing `mysqldb` service defined in the main project.
# In each environment (e.g. `chatbot`, `dev`, `master`), `mysqldb` is a separate DB instance.
relationships:
  configdb: "mysqldb:chatbot"

# Environment variables
# Secrets (ALGOLIA_APP_ID, ALGOLIA_API_KEY, OPENAI_API_KEY) set via Platform.sh portal
variables:
  env:
    # Python/Uvicorn settings
    PYTHONUNBUFFERED: "1"
    # CORS configuration
    CORS_ORIGINS: "*"

# Resources allocation
resources:
  base_memory: 128
  memory_ratio: 256

# Cron jobs
crons:
  update_vectordb:
    # Run daily at 4:00 AM EST (9:00 AM UTC)
    # Note: During EDT (daylight saving), this will run at 5:00 AM EDT
    spec: '0 9 * * *'
    commands:
      start: 'python update_vector_db.py'

  daily_analytics_email:
    # Run daily at ~8:00 AM EST (13:00 UTC)
    # Note: During EDT this will fire at 9:00 AM EDT
    spec: '0 13 * * *'
    commands:
      start: 'python daily_analytics_email.py'

