# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^wordpress_/', '/^wp-settings/']
    redirects:
      expires: 1d
      paths:
        '^/wp-admin$':
          to: "/wp/wp-admin/"
          regexp: true
        '^/wp-admin/(.*)':
          to: "/wp/wp-admin/$1"
          regexp: true
########## ACADEMIC DEPARTMENTS ##########
        # African-American Studies
        '^/african-american/(.*)$':
          to: '/academics/departments-and-programs/african-american-studies/$1'
          regexp: true
        '^/african-american/?$':
          to: '/academics/departments-and-programs/african-american-studies/'
          regexp: true
        '^/african-american/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/african-american-studies/$1/'
          regexp: true
        '^/africanamerican/(.*)$':
          to: '/academics/departments-and-programs/african-american-studies/$1'
          regexp: true
        '^/africanamerican/?$':
          to: '/academics/departments-and-programs/african-american-studies/'
          regexp: true
        '^/africanamerican/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/african-american-studies/$1/'
          regexp: true
        # American Studies
        '^/american-studies/(.*)$':
          to: '/academics/departments-and-programs/american-studies/$1'
          regexp: true
        '^/american-studies/?$':
          to: '/academics/departments-and-programs/american-studies/'
          regexp: true
        '^/american-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/american-studies/$1/'
          regexp: true
        '^/americanstudies/(.*)$':
          to: '/academics/departments-and-programs/american-studies/$1'
          regexp: true
        '^/americanstudies/?$':
          to: '/academics/departments-and-programs/american-studies/'
          regexp: true
        '^/americanstudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/american-studies/$1/'
          regexp: true
        # Anthropology
        '^/anthropology/(.*)$':
          to: '/academics/departments-and-programs/anthropology/$1'
          regexp: true
        '^/anthropology/?$':
          to: '/academics/departments-and-programs/anthropology/'
          regexp: true
        '^/anthropology/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/anthropology/$1/'
          regexp: true
        '^/anthro/(.*)$':
          to: '/academics/departments-and-programs/anthropology/$1'
          regexp: true
        '^/anthro/?$':
          to: '/academics/departments-and-programs/anthropology/'
          regexp: true
        '^/anthro/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/anthropology/$1/'
          regexp: true
        # Art
        '^/art/(.*)$':
          to: '/academics/departments-and-programs/art/$1'
          regexp: true
        '^/art/?$':
          to: '/academics/departments-and-programs/art/'
          regexp: true
        '^/art/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/art/$1/'
          regexp: true
        '^/artdept/(.*)$':
          to: '/academics/departments-and-programs/art/$1'
          regexp: true
        '^/artdept/?$':
          to: '/academics/departments-and-programs/art/'
          regexp: true
        '^/artdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/art/$1/'
          regexp: true
        # Biology
        '^/biology/(.*)$':
          to: '/academics/departments-and-programs/biology/$1'
          regexp: true
        '^/biology/?$':
          to: '/academics/departments-and-programs/biology/'
          regexp: true
        '^/biology/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/biology/$1/'
          regexp: true
        '^/bio/(.*)$':
          to: '/academics/departments-and-programs/biology/$1'
          regexp: true
        '^/bio/?$':
          to: '/academics/departments-and-programs/biology/'
          regexp: true
        '^/bio/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/biology/$1/'
          regexp: true
        # Chemistry
        '^/chemistry/(.*)$':
          to: '/academics/departments-and-programs/chemistry/$1'
          regexp: true
        '^/chemistry/?$':
          to: '/academics/departments-and-programs/chemistry/'
          regexp: true
        '^/chemistry/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/chemistry/$1/'
          regexp: true
        '^/chem/(.*)$':
          to: '/academics/departments-and-programs/chemistry/$1'
          regexp: true
        '^/chem/?$':
          to: '/academics/departments-and-programs/chemistry/'
          regexp: true
        '^/chem/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/chemistry/$1/'
          regexp: true
        # Cinema Studies
        '^/cinema-studies/(.*)$':
          to: '/academics/departments-and-programs/cinema-studies/$1'
          regexp: true
        '^/cinema-studies/?$':
          to: '/academics/departments-and-programs/cinema-studies/'
          regexp: true
        '^/cinema-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/cinema-studies/$1/'
          regexp: true
        '^/cinemastudies/(.*)$':
          to: '/academics/departments-and-programs/cinema-studies/$1'
          regexp: true
        '^/cinemastudies/?$':
          to: '/academics/departments-and-programs/cinema-studies/'
          regexp: true
        '^/cinemastudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/cinema-studies/$1/'
          regexp: true
        # Classics
        '^/classics/(.*)$':
          to: '/academics/departments-and-programs/classics/$1'
          regexp: true
        '^/classics/?$':
          to: '/academics/departments-and-programs/classics/'
          regexp: true
        '^/classics/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/classics/$1/'
          regexp: true
        '^/classicsdept/(.*)$':
          to: '/academics/departments-and-programs/classics/$1'
          regexp: true
        '^/classicsdept/?$':
          to: '/academics/departments-and-programs/classics/'
          regexp: true
        '^/classicsdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/classics/$1/'
          regexp: true
          # Computer Science
        '^/computer-science/(.*)$':
          to: '/academics/departments-and-programs/computer-science/$1'
          regexp: true
        '^/computer-science/?$':
          to: '/academics/departments-and-programs/computer-science/'
          regexp: true
        '^/computer-science/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/computer-science/$1/'
          regexp: true
        '^/computerscience/(.*)$':
          to: '/academics/departments-and-programs/computer-science/$1'
          regexp: true
        '^/computerscience/?$':
          to: '/academics/departments-and-programs/computer-science/'
          regexp: true
        '^/computerscience/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/computer-science/$1/'
          regexp: true
        # Creative Writing
        '^/creative-writing/(.*)$':
          to: '/academics/departments-and-programs/creative-writing/$1'
          regexp: true
        '^/creative-writing/?$':
          to: '/academics/departments-and-programs/creative-writing/'
          regexp: true
        '^/creative-writing/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/creative-writing/$1/'
          regexp: true
        '^/cwriting/(.*)$':
          to: '/academics/departments-and-programs/creative-writing/$1'
          regexp: true
        '^/cwriting/?$':
          to: '/academics/departments-and-programs/creative-writing/'
          regexp: true
        '^/cwriting/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/creative-writing/$1/'
          regexp: true
        '^/creativewriting/(.*)$':
          to: '/academics/departments-and-programs/creative-writing/$1'
          regexp: true
        '^/creativewriting/?$':
          to: '/academics/departments-and-programs/creative-writing/'
          regexp: true
        '^/creativewriting/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/creative-writing/$1/'
          regexp: true
          # East Asian Studies
        '^/east-asian-studies/(.*)$':
          to: '/academics/departments-and-programs/east-asian-studies/$1'
          regexp: true
        '^/east-asian-studies/?$':
          to: '/academics/departments-and-programs/east-asian-studies/'
          regexp: true
        '^/east-asian-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/east-asian-studies/$1/'
          regexp: true
        '^/eastasianstudies/(.*)$':
          to: '/academics/departments-and-programs/east-asian-studies/$1'
          regexp: true
        '^/eastasianstudies/?$':
          to: '/academics/departments-and-programs/east-asian-studies/'
          regexp: true
        '^/eastasianstudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/east-asian-studies/$1/'
          regexp: true
          # Economics
        '^/economics/(.*)$':
          to: '/academics/departments-and-programs/economics/$1'
          regexp: true
        '^/economics/?$':
          to: '/academics/departments-and-programs/economics/'
          regexp: true
        '^/economics/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/economics/$1/'
          regexp: true
        '^/econ/(.*)$':
          to: '/academics/departments-and-programs/economics/$1'
          regexp: true
        '^/econ/?$':
          to: '/academics/departments-and-programs/economics/'
          regexp: true
        '^/econ/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/economics/$1/'
          regexp: true
        # Education
        '^/education/(.*)$':
          to: '/academics/departments-and-programs/education/$1'
          regexp: true
        '^/education/?$':
          to: '/academics/departments-and-programs/education/'
          regexp: true
        '^/education/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/education/$1/'
          regexp: true
        # English
        '^/english/(.*)$':
          to: '/academics/departments-and-programs/english/$1'
          regexp: true
        '^/english/?$':
          to: '/academics/departments-and-programs/english/'
          regexp: true
        '^/english/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/english/$1/'
          regexp: true
        '^/englishdept/(.*)$':
          to: '/academics/departments-and-programs/english/$1'
          regexp: true
        '^/englishdept/?$':
          to: '/academics/departments-and-programs/english/'
          regexp: true
        '^/englishdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/english/$1/'
          regexp: true
        # Environmental Studies
        '^/environmental-studies/(.*)$':
          to: '/academics/departments-and-programs/environmental-studies/$1'
          regexp: true
        '^/environmental-studies/?$':
          to: '/academics/departments-and-programs/environmental-studies/'
          regexp: true
        '^/environmental-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/environmental-studies/$1/'
          regexp: true
        '^/environmentalstudies/(.*)$':
          to: '/academics/departments-and-programs/environmental-studies/$1'
          regexp: true
        '^/environmentalstudies/?$':
          to: '/academics/departments-and-programs/environmental-studies/'
          regexp: true
        '^/environmentalstudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/environmental-studies/$1/'
          regexp: true
        # French and Italian
        '^/french-and-italian/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/french-and-italian/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/french-and-italian/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/frenchanditalian/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/frenchanditalian/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/frenchanditalian/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/frenchitalian/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/frenchitalian/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/frenchitalian/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/italian-and-french/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/italian-and-french/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/italian-and-french/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/italianandfrench/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/italianandfrench/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/italianandfrench/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/italianfrench/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/italianfrench/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/italianfrench/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/french/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/french/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/french/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
        '^/italian/(.*)$':
          to: '/academics/departments-and-programs/french-and-italian/$1'
          regexp: true
        '^/italian/?$':
          to: '/academics/departments-and-programs/french-and-italian/'
          regexp: true
        '^/italian/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/french-and-italian/$1/'
          regexp: true
########## OFFICES ##########
        # ITS
        '^/its/(.*)$':
          to: '/people/offices-directory/information-technology-services/$1'
          regexp: true
        '^/its/?$':
          to: '/people/offices-directory/information-technology-services/'
          regexp: true
        '^/its/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/people/offices-directory/information-technology-services/$1/'
          regexp: true
########## MISC. ROOT LEVEL SITES ##########
        # Visitors
        # '^/visitors/(.*)$':
        #   to: '/visitors/$1'
        #   regexp: true
        # '^/visitors/$':
        #   to: '/visitors/'
        #   regexp: true
        '^/visitors/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/visitors/$1/'
          regexp: true

        # January Program
        '^/januaryprogram/(.*)$':
          to: '/january-program/$1'
          regexp: true
        '^/januaryprogram/$':
          to: '/january-program/'
          regexp: true
        '^/januaryprogram/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/january-program/$1/'
          regexp: true

# *ALL* www.* requests should be redirected back to primary domain
"https://www.{all}/":
    type: redirect
    to: "https://{default}/"
# All vanity domain requests should be redirected to primary domain
"https://{all}/":
  type: redirect
  to: "https://{default}/"
