# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^wordpress_/', '/^wp-settings/']
    redirects:
      expires: 1d
      paths:
        '^/wp-admin$':
          to: "/wp/wp-admin/"
          regexp: true
        '^/wp-admin/(.*)':
          to: "/wp/wp-admin/$1"
          regexp: true
########## ACADEMIC DEPARTMENTS ##########
        # african american studies
        '^/african-american/(.*)$':
          to: '/academics/departments-and-programs/african-american-studies/$1'
          regexp: true
        '^/african-american/?$':
          to: '/academics/departments-and-programs/african-american-studies/'
          regexp: true
        '^/african-american/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/african-american-studies/$1/'
          regexp: true
        '^/africanamerican/(.*)$':
          to: '/academics/departments-and-programs/african-american-studies/$1'
          regexp: true
        '^/africanamerican/?$':
          to: '/academics/departments-and-programs/african-american-studies/'
          regexp: true
        '^/africanamerican/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/african-american-studies/$1/'
          regexp: true
        # american studies
        '^/american-studies/(.*)$':
          to: '/academics/departments-and-programs/american-studies/$1'
          regexp: true
        '^/american-studies/?$':
          to: '/academics/departments-and-programs/american-studies/'
          regexp: true
        '^/american-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/american-studies/$1/'
          regexp: true
        '^/americanstudies/(.*)$':
          to: '/academics/departments-and-programs/american-studies/$1'
          regexp: true
        '^/americanstudies/?$':
          to: '/academics/departments-and-programs/american-studies/'
          regexp: true
        '^/americanstudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/american-studies/$1/'
          regexp: true
        # anthropology
        '^/anthropology/(.*)$':
          to: '/academics/departments-and-programs/anthropology/$1'
          regexp: true
        '^/anthropology/?$':
          to: '/academics/departments-and-programs/anthropology/'
          regexp: true
        '^/anthropology/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/anthropology/$1/'
          regexp: true
        '^/anthro/(.*)$':
          to: '/academics/departments-and-programs/anthropology/$1'
          regexp: true
        '^/anthro/?$':
          to: '/academics/departments-and-programs/anthropology/'
          regexp: true
        '^/anthro/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/anthropology/$1/'
          regexp: true
        # art
        '^/art/(.*)$':
          to: '/academics/departments-and-programs/art/$1'
          regexp: true
        '^/art/?$':
          to: '/academics/departments-and-programs/art/'
          regexp: true
        '^/art/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/art/$1/'
          regexp: true
        '^/artdept/(.*)$':
          to: '/academics/departments-and-programs/art/$1'
          regexp: true
        '^/artdept/?$':
          to: '/academics/departments-and-programs/art/'
          regexp: true
        '^/artdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/art/$1/'
          regexp: true
        # Biology
        '^/biology/(.*)$':
          to: '/academics/departments-and-programs/biology/$1'
          regexp: true
        '^/biology/?$':
          to: '/academics/departments-and-programs/biology/'
          regexp: true
        '^/biology/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/biology/$1/'
          regexp: true
        '^/bio/(.*)$':
          to: '/academics/departments-and-programs/biology/$1'
          regexp: true
        '^/bio/?$':
          to: '/academics/departments-and-programs/biology/'
          regexp: true
        '^/bio/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/biology/$1/'
          regexp: true
        # Chemistry
        '^/chemistry/(.*)$':
          to: '/academics/departments-and-programs/chemistry/$1'
          regexp: true
        '^/chemistry/?$':
          to: '/academics/departments-and-programs/chemistry/'
          regexp: true
        '^/chemistry/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/chemistry/$1/'
          regexp: true
        '^/chem/(.*)$':
          to: '/academics/departments-and-programs/chemistry/$1'
          regexp: true
        '^/chem/?$':
          to: '/academics/departments-and-programs/chemistry/'
          regexp: true
        '^/chem/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/chemistry/$1/'
          regexp: true
        # Cinema Studies
        '^/cinema-studies/(.*)$':
          to: '/academics/departments-and-programs/cinema-studies/$1'
          regexp: true
        '^/cinema-studies/?$':
          to: '/academics/departments-and-programs/cinema-studies/'
          regexp: true
        '^/cinema-studies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/cinema-studies/$1/'
          regexp: true
        '^/cinemastudies/(.*)$':
          to: '/academics/departments-and-programs/cinema-studies/$1'
          regexp: true
        '^/cinemastudies/?$':
          to: '/academics/departments-and-programs/cinema-studies/'
          regexp: true
        '^/cinemastudies/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/cinema-studies/$1/'
          regexp: true
        # Classics
        '^/classics/(.*)$':
          to: '/academics/departments-and-programs/classics/$1'
          regexp: true
        '^/classics/?$':
          to: '/academics/departments-and-programs/classics/'
          regexp: true
        '^/classics/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/classics/$1/'
          regexp: true
        '^/classicsdept/(.*)$':
          to: '/academics/departments-and-programs/classics/$1'
          regexp: true
        '^/classicsdept/?$':
          to: '/academics/departments-and-programs/classics/'
          regexp: true
        '^/classicsdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/classics/$1/'
          regexp: true
          # Computer Science
        '^/computer-science/(.*)$':
          to: '/academics/departments-and-programs/computer-science/$1'
          regexp: true
        '^/computer-science/?$':
          to: '/academics/departments-and-programs/computer-science/'
          regexp: true
        '^/computer-science/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/computer-science/$1/'
          regexp: true
        '^/computerscience/(.*)$':
          to: '/academics/departments-and-programs/computer-science/$1'
          regexp: true
        '^/computerscience/?$':
          to: '/academics/departments-and-programs/computer-science/'
          regexp: true
        '^/computerscience/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/computer-science/$1/'
          regexp: true
########## OFFICES ##########
        # ITS
        '^/its/(.*)$':
          to: '/people/offices-directory/information-technology-services/$1'
          regexp: true
        '^/its/?$':
          to: '/people/offices-directory/information-technology-services/'
          regexp: true
        '^/its/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/people/offices-directory/information-technology-services/$1/'
          regexp: true
########## MISC. ROOT LEVEL SITES ##########
        # Visitors
        # '^/visitors/(.*)$':
        #   to: '/visitors/$1'
        #   regexp: true
        # '^/visitors/$':
        #   to: '/visitors/'
        #   regexp: true
        '^/visitors/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/visitors/$1/'
          regexp: true

        # January Program
        '^/januaryprogram/(.*)$':
          to: '/january-program/$1'
          regexp: true
        '^/januaryprogram/$':
          to: '/january-program/'
          regexp: true
        '^/januaryprogram/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/january-program/$1/'
          regexp: true

# *ALL* www.* requests should be redirected back to primary domain
"https://www.{all}/":
    type: redirect
    to: "https://{default}/"
# All vanity domain requests should be redirected to primary domain
"https://{all}/":
  type: redirect
  to: "https://{default}/"
