# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^wordpress_/', '/^wp-settings/']
    redirects:
      expires: 1d
      paths:
        '^/wp-admin$':
          to: "/wp/wp-admin/"
          regexp: true
        '^/wp-admin/(.*)':
          to: "/wp/wp-admin/$1"
          regexp: true
        
        # art
        '^/artdept/(.*)$':
          to: '/academics/departments-and-programs/art/$1'
          regexp: true
        '^/artdept/?$':
          to: '/academics/departments-and-programs/art/'
          regexp: true
        '^/artdept/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/academics/departments-and-programs/art/$1/'
          regexp: true

        # ITS
        '^/its/(.*)$':
          to: '/people/offices-directory/information-technology-services/$1'
          regexp: true
        '^/its/?$':
          to: '/people/offices-directory/information-technology-services/'
          regexp: true
        '^/its/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/people/offices-directory/information-technology-services/$1/'
          regexp: true

        # Visitors
        '^/visitors/(.*)$':
          to: '/visitors/$1'
          regexp: true
        '^/visitors/$':
          to: '/visitors/'
          regexp: true
        '^/visitors/\d{4}/\d{2}/\d{2}/(.+)/?$':
          to: '/visitors/$1/'
          regexp: true





# *ALL* www.* requests should be redirected back to primary domain
"https://www.{all}/":
    type: redirect
    to: "https://{default}/"
# All vanity domain requests should be redirected to primary domain
"https://{all}/":
  type: redirect
  to: "https://{default}/"
