name: Algolia Aggregation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
env:
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
jobs:
  aggregate_algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: node ./scripts/algolia_aggregation.js --algoliaAppId=${{ secrets.ALGOLIA_APP_ID }} --algoliaApiKey=${{ secrets.ALGOLIA_API_KEY }} --algoliaIndicies='${{ secrets.ALGOLIA_INDICIES }}'