name: Lighthouse 
on:
  workflow_dispatch:
  push:
    branches:
      - 'inertia'
jobs:
  run_lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: '.github/.lighthouserc.json'
          uploadArtifacts: true # Upload reports to GitHub Actions
     